account_type:
  ar: "ar"
  ap: "ap"

cash_types:
  bank: "bank"
  safe: "safe"

voucher_types:
  civ: "civ"
  cov: "cov"

company:
  branch: "PNP"

confirm_modal_types:
  has_children: "has_children"
  active: "active"
  inactive: "inactive"
  destroy: "destroy"
  data_used: "data_used"

commit_params:
  save_new: "Save new"
  save_close: "Save close"
